### ISSUE TITLE
Typo/error in documentation

### ISSUE THREAD

**Issue by ault** [KOBENDigital/bento.editor#16]
in the templating section...

`@foreach(Bento.Core.Models.StackItem layout in Model.MyBentoStackProperty){`
 ` <section>`
`      @Html.Partial($"~/Views/Partials/Bento/layouts/{item.Alias}.cshtml", item)`
`  </section>`
`}`

In these lines, 'item' should be 'layout'

**Comment by pgregorynz** [comment]
Fixed in commit 13e855b
