### ISSUE TITLE
Saving error: Cannot deserialize JSON

### ISSUE THREAD

**Issue by Jojov11** [KOBENDigital/bento.editor#18]
Hi,

when I try save content with "**Grid layout**" data type, I get this error:

> Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Bento.Core.Models.StackItem]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'name', line 1, position 8.

> Exception Details
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Bento.Core.Models.StackItem]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'name', line 1, position 8.

I found a problem in Bento.Core.Events.ContentServiceEvents.ContentService_Saved on line 154
https://github.com/KOBENDigital/bento.editor/blob/9b109634174ffd5a768154b4b820b5c10fc5d985/src/Bento.Core/Events/ContentServiceEvents.cs#L154

Grid layout can't bind to StackItem model.

Is this bug or I do something wrong?
THX.

**Comment by pgregorynz** [comment]
This looks like its related to one of the data types you have on your document type. Could you let me know data types you are using?

**Comment by Jojov11** [comment]
I think "Grid layout" is problematic data type.
Data types on saving page:
- Textbox
- Grid Layout
- Content picker ( not picked any content )
- Bento Stack
- Tags
- Media Picker

Data types on inserting content to bento stack are same as saving page.

Anyway I got this error every time I save page / element with "Grid Layout" data type.

**Comment by Jojov11** [comment]
Explain what i want:
I want create a small components / content blocks which I linked to content page.

Example: I crate components "contact info", "google map embed", "image gallery". Then I create "Contact  Page" and insert this components to this page. Next I create "About page" and here insert only two components.
When I edit component "contact info" they will have updated content on all pages when is inserted.

**Comment by pgregorynz** [comment]
Yes it will be the Grid Layout that is causing the explosion as it wont boil down to a strong type.

Are you using element types or using library types for your Bento blocks?  If you use a bento library item (IPublishedContent) you can create and reuse blocks.  IPubllishedElements are one use items that only exist in bento stack.

**Comment by Jojov11** [comment]
I use a bento library item but this item contain "Grid Layout" data type :/ 

I think this error is a problem with the "Usage" module because the content is saved when I add "try catch" statement.

**Comment by pgregorynz** [comment]
Unable to replicate.
