### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by No1sBothered** [KOBENDigital/bento.editor#33]
I am not seeing much activity on this project, there are pull requests outstanding.

Please can you let me know if the project is dead or when and if the pull requests will be added and if people should be using Bento in production?

**Comment by pgregorynz** [comment]
Thanks for reaching out.  No.  Definitely not dead, we had a small hiatus due to COVID and other reasons.  We are coming back at this hard in the next few months as Umbraco 9 will require us to refactor portions for which the work has already begun.

**Comment by No1sBothered** [comment]
you beautiful people, keep up the excellent work!
