### ISSUE TITLE
Difficulty getting started

### ISSUE THREAD

**Issue by hifi-phil** [KOBENDigital/bento.editor#7]
I think I've got myself into a bit of a mess whilst trying to setup. I followed the instructions in the readme but I keep getting an error when saving a content node that contains Bento 

A duplicate value cannot be inserted into a unique index. [ Table name = umbracoRelationType,Constraint name = IX_umbracoRelationType_name ]

I think this relates to the bentoitems RelationType. When I delete it I can save again but the error keeps coming back. 

Is there an order that I need to set up all the elements in?

**Comment by hifi-phil** [comment]
Had a look at the source and tracked down a bug, left a pull request. It was edited in Github so hopefully, it merges OK!

Everything is working now!

**Comment by EwneoN** [comment]
Hi @hifi-phil, thank you for tracking this one down and putting in a fix. I was going to have a look at it myself but you have beaten me to it.
